version: "3.0"
services:
  rasa:
    image: rasa/rasa:3.6.0-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: rasa/rasa-sdk:3.6.0
    expose:
      - "5055"
#ssh keygen gen
#tmux

